### ISSUE TITLE
Instalar-ho

### ISSUE THREAD

**Issue by Dimavj** [lubalee/woocommerce-ca#1]
Hola. he buscat i no he trobat una bona explicació de com instalar el _ca al plugin woocomerce, 
alguns diuen coses diferents... 
algú em pot donar alguna indicació¿
Gracies!
A

**Comment by mananipons** [comment]
Hola!
Doncs la millor manera de tenir les traduccions en Wordpress, i que al actualitzar els plugins, no sobreescriguis (i les perdis) has de fer el següent:

Posar els woocommerce-ca.po i .mo a wp-content/languages/plugins.

Simplement això. I això serveix per qualsevol plugin.

Fins ara.

**Comment by lubalee** [comment]
Ei!!

Comparteixo el que diu el @mananipons: per evitar sobreescriure arxius en actualitzar el plugin, el més segur és que els posis a **/wp-content/languages/plugins/**. I, en el cas de traduccions de temes, a la carpeta **/wp-content/languages/themes/**.

Ara bé, si preguntes específicament en aquest cas, en teoria la ruta actual, dins la carpeta del WooCommerce, seria: **/wp-content/plugins/woocommerce/i18n/languages/**.

En els dos casos funciona igualment bé.

Pel que fa als arxius amb la traducció, la cosa ha anat canviant diverses vegades. Actualment, la més completa (i oficial) la trobaràs aquí: [https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/ca/default](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/ca/default)

Has de descarregar-te els dos arxius i posar-los al teu servidor. 

Precisament estic fent una entrada que explica el tema. Així que la tingui us passo l'enllaç :)

**Comment by Dimavj** [comment]
Ep nois, Gràcies, ja ho tinc!
Salutacions!
A.
